import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'ar' | 'en';
  setLanguage: (lang: 'ar' | 'en') => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    // Navigation & Basic
    home: 'الرئيسية',
    exploreNav: 'استكشف',
    services: 'الخدمات',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    dashboard: 'لوحة التحكم',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    
    // Index Page
    index: {
      welcomeBack: 'مرحباً بعودتك',
      discoverEvents: 'اكتشف أحدث الفعاليات والأنشطة',
      featuredEvents: 'الفعاليات المميزة',
      popularCategories: 'الفئات الشائعة',
      upcomingEvents: 'الفعاليات القادمة',
      joinAdventure: 'انضم إلى المغامرة',
      bookNow: 'احجز الآن',
      learnMore: 'اعرف المزيد',
      adventureAwaits: 'المغامرة في انتظارك',
      getStarted: 'ابدأ الآن',
      exploreNow: 'استكشف الآن',
    },

    // Explore Page
    explore: {
      title: 'استكشاف الفعاليات',
      searchPlaceholder: 'ابحث عن الفعاليات...',
      allCategories: 'جميع الفئات',
      allEvents: 'جميع الفعاليات',
      noEvents: 'لا توجد فعاليات متاحة حالياً',
      filterByDate: 'تصفية حسب التاريخ',
      filterByPrice: 'تصفية حسب السعر',
      filterByLocation: 'تصفية حسب الموقع',
      sortBy: 'ترتيب حسب',
      newest: 'الأحدث',
      oldest: 'الأقدم',
      priceHighToLow: 'السعر: من الأعلى للأقل',
      priceLowToHigh: 'السعر: من الأقل للأعلى',
      popularity: 'الأكثر شعبية',
      clearFilters: 'مسح الفلاتر',
      results: 'نتيجة',
      free: 'مجاني',
      riyal: 'ريال',
    },

    // Services Page
    servicesPage: {
      title: 'الخدمات المتاحة',
      subtitle: 'اكتشف الخدمات المميزة لتجربة أفضل',
      searchServices: 'ابحث عن الخدمات...',
      allServices: 'جميع الخدمات',
      noServices: 'لا توجد خدمات متاحة حالياً',
      requestService: 'طلب الخدمة',
      serviceDetails: 'تفاصيل الخدمة',
      duration: 'المدة',
      minutes: 'دقيقة',
      hours: 'ساعة',
      days: 'يوم',
      available: 'متاح',
      unavailable: 'غير متاح',
      contactProvider: 'اتصل بمقدم الخدمة',
    },

    // Event Details
    eventDetails: {
      title: 'تفاصيل الفعالية',
      description: 'الوصف',
      location: 'الموقع',
      dateTime: 'التاريخ والوقت',
      price: 'السعر',
      organizer: 'المنظم',
      category: 'الفئة',
      capacity: 'السعة',
      available: 'متاح',
      soldOut: 'نفدت التذاكر',
      bookTicket: 'احجز تذكرة',
      shareEvent: 'شارك الفعالية',
      addToCalendar: 'أضف للتقويم',
      eventHighlights: 'أبرز المعالم',
      requirements: 'المتطلبات',
      whatToExpect: 'ما تتوقعه',
      safetyGuidelines: 'إرشادات السلامة',
      reviews: 'التقييمات',
      rating: 'التقييم',
      noReviews: 'لا توجد تقييمات بعد',
      writeReview: 'اكتب تقييماً',
      similarEvents: 'فعاليات مشابهة',
      eventRules: 'قوانين الفعالية',
      cancellationPolicy: 'سياسة الإلغاء',
      contactOrganizer: 'تواصل مع المنظم',
      reportEvent: 'الإبلاغ عن الفعالية',
    },

    // Service Details
    serviceDetails: {
      title: 'تفاصيل الخدمة',
      description: 'الوصف',
      provider: 'مقدم الخدمة',
      duration: 'المدة',
      price: 'السعر',
      location: 'الموقع',
      availability: 'التوفر',
      features: 'المميزات',
      requestService: 'طلب الخدمة',
      contactProvider: 'تواصل مع المقدم',
      serviceIncludes: 'تشمل الخدمة',
      serviceExcludes: 'لا تشمل الخدمة',
      bookingPolicy: 'سياسة الحجز',
      cancellationPolicy: 'سياسة الإلغاء',
      reviews: 'التقييمات',
      rating: 'التقييم',
      writeReview: 'اكتب تقييماً',
      similarServices: 'خدمات مشابهة',
      reportService: 'الإبلاغ عن الخدمة',
      shareService: 'شارك الخدمة',
    },

    // Dashboard
    dashboardPage: {
      title: 'لوحة التحكم',
      welcome: 'مرحباً',
      quickStats: 'إحصائيات سريعة',
      totalBookings: 'إجمالي الحجوزات',
      upcomingEvents: 'الفعاليات القادمة',
      totalSpent: 'إجمالي المبلغ المنفق',
      loyaltyPoints: 'نقاط الولاء',
      recentActivity: 'النشاط الأخير',
      bookingHistory: 'تاريخ الحجوزات',
      favorites: 'المفضلة',
      recommendations: 'التوصيات',
      quickActions: 'إجراءات سريعة',
      exploreEvents: 'استكشف الفعاليات',
      browseServices: 'تصفح الخدمات',
      manageProfile: 'إدارة الملف الشخصي',
      viewTickets: 'عرض التذاكر',
      checkWallet: 'فحص المحفظة',
      overview: 'نظرة عامة',
      analytics: 'التحليلات',
      reports: 'التقارير',
      settings: 'الإعدادات',
      notifications: 'الإشعارات',
      messages: 'الرسائل',
    },

    // Profile
    profilePage: {
      title: 'الملف الشخصي',
      personalInfo: 'المعلومات الشخصية',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      dateOfBirth: 'تاريخ الميلاد',
      gender: 'الجنس',
      nationality: 'الجنسية',
      city: 'المدينة',
      interests: 'الاهتمامات',
      bio: 'نبذة عني',
      profilePicture: 'الصورة الشخصية',
      changePassword: 'تغيير كلمة المرور',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
      updateProfile: 'تحديث الملف الشخصي',
      accountSettings: 'إعدادات الحساب',
      privacySettings: 'إعدادات الخصوصية',
      notificationPreferences: 'تفضيلات الإشعارات',
      deleteAccount: 'حذف الحساب',
      accountType: 'نوع الحساب',
      memberSince: 'عضو منذ',
      lastActive: 'آخر نشاط',
      verificationStatus: 'حالة التحقق',
      verified: 'محقق',
      unverified: 'غير محقق',
      verifyAccount: 'تحقق من الحساب',
    },

    // Settings
    settingsPage: {
      title: 'الإعدادات',
      general: 'عام',
      account: 'الحساب',
      privacy: 'الخصوصية',
      notifications: 'الإشعارات',
      security: 'الأمان',
      language: 'اللغة',
      theme: 'المظهر',
      currency: 'العملة',
      timezone: 'المنطقة الزمنية',
      emailNotifications: 'إشعارات البريد الإلكتروني',
      smsNotifications: 'إشعارات الرسائل النصية',
      pushNotifications: 'الإشعارات المنبثقة',
      marketingEmails: 'رسائل تسويقية',
      eventReminders: 'تذكيرات الفعاليات',
      bookingConfirmations: 'تأكيدات الحجز',
      newEventAlerts: 'تنبيهات الفعاليات الجديدة',
      twoFactorAuth: 'المصادقة الثنائية',
      loginAlerts: 'تنبيهات تسجيل الدخول',
      deviceManagement: 'إدارة الأجهزة',
      sessionHistory: 'تاريخ الجلسات',
      dataDownload: 'تحميل البيانات',
      accountDeletion: 'حذف الحساب',
      lightMode: 'الوضع الفاتح',
      darkMode: 'الوضع المظلم',
      systemDefault: 'افتراضي النظام',
      enable: 'تفعيل',
      disable: 'إيقاف',
      saveChanges: 'حفظ التغييرات',
      resetToDefault: 'إعادة تعيين للافتراضي',
    },

    // Create Event
    createEvent: {
      title: 'إنشاء فعالية جديدة',
      basicInfo: 'المعلومات الأساسية',
      eventTitle: 'عنوان الفعالية',
      eventDescription: 'وصف الفعالية',
      category: 'الفئة',
      selectCategory: 'اختر الفئة',
      eventImage: 'صورة الفعالية',
      uploadImage: 'رفع صورة',
      dateTime: 'التاريخ والوقت',
      startDate: 'تاريخ البداية',
      endDate: 'تاريخ النهاية',
      startTime: 'وقت البداية',
      endTime: 'وقت النهاية',
      location: 'الموقع',
      venue: 'المكان',
      address: 'العنوان',
      onlineEvent: 'فعالية عبر الإنترنت',
      meetingLink: 'رابط الاجتماع',
      pricing: 'التسعير',
      freeEvent: 'فعالية مجانية',
      paidEvent: 'فعالية مدفوعة',
      ticketPrice: 'سعر التذكرة',
      currency: 'العملة',
      capacity: 'السعة',
      maxAttendees: 'الحد الأقصى للحضور',
      minAttendees: 'الحد الأدنى للحضور',
      registrationDeadline: 'موعد انتهاء التسجيل',
      requirements: 'المتطلبات',
      ageRestriction: 'قيود العمر',
      equipmentNeeded: 'المعدات المطلوبة',
      fitnessLevel: 'مستوى اللياقة',
      specialRequirements: 'متطلبات خاصة',
      additionalInfo: 'معلومات إضافية',
      eventRules: 'قوانين الفعالية',
      cancellationPolicy: 'سياسة الإلغاء',
      refundPolicy: 'سياسة الاسترداد',
      contactInfo: 'معلومات التواصل',
      organizerName: 'اسم المنظم',
      organizerEmail: 'بريد المنظم الإلكتروني',
      organizerPhone: 'هاتف المنظم',
      createEvent: 'إنشاء الفعالية',
      saveDraft: 'حفظ كمسودة',
      preview: 'معاينة',
      publish: 'نشر',
      eventCreated: 'تم إنشاء الفعالية بنجاح',
      eventSaved: 'تم حفظ الفعالية كمسودة',
    },

    // Create Service
    createService: {
      title: 'إنشاء خدمة جديدة',
      basicInfo: 'المعلومات الأساسية',
      serviceName: 'اسم الخدمة',
      serviceDescription: 'وصف الخدمة',
      category: 'الفئة',
      selectCategory: 'اختر الفئة',
      serviceImage: 'صورة الخدمة',
      uploadImage: 'رفع صورة',
      pricing: 'التسعير',
      servicePrice: 'سعر الخدمة',
      currency: 'العملة',
      duration: 'المدة',
      minutes: 'دقيقة',
      hours: 'ساعة',
      days: 'يوم',
      location: 'الموقع',
      serviceLocation: 'موقع تقديم الخدمة',
      onlineService: 'خدمة عبر الإنترنت',
      homeService: 'خدمة منزلية',
      officeService: 'خدمة مكتبية',
      availability: 'التوفر',
      workingHours: 'ساعات العمل',
      workingDays: 'أيام العمل',
      availableSlots: 'المواعيد المتاحة',
      features: 'المميزات',
      serviceIncludes: 'تشمل الخدمة',
      serviceExcludes: 'لا تشمل الخدمة',
      requirements: 'المتطلبات',
      equipmentProvided: 'المعدات المقدمة',
      clientRequirements: 'متطلبات العميل',
      additionalInfo: 'معلومات إضافية',
      serviceTerms: 'شروط الخدمة',
      cancellationPolicy: 'سياسة الإلغاء',
      refundPolicy: 'سياسة الاسترداد',
      contactInfo: 'معلومات التواصل',
      providerName: 'اسم مقدم الخدمة',
      providerEmail: 'بريد مقدم الخدمة',
      providerPhone: 'هاتف مقدم الخدمة',
      createService: 'إنشاء الخدمة',
      saveDraft: 'حفظ كمسودة',
      preview: 'معاينة',
      publish: 'نشر',
      serviceCreated: 'تم إنشاء الخدمة بنجاح',
      serviceSaved: 'تم حفظ الخدمة كمسودة',
    },

    // Wallet
    wallet: {
      title: 'المحفظة',
      balance: 'الرصيد',
      availableBalance: 'الرصيد المتاح',
      pendingAmount: 'المبلغ المعلق',
      totalSpent: 'إجمالي المبلغ المنفق',
      totalEarned: 'إجمالي المبلغ المكتسب',
      transactions: 'المعاملات',
      recentTransactions: 'المعاملات الأخيرة',
      allTransactions: 'جميع المعاملات',
      income: 'دخل',
      expense: 'مصروف',
      transfer: 'تحويل',
      refund: 'استرداد',
      commission: 'عمولة',
      addMoney: 'إضافة أموال',
      withdrawMoney: 'سحب أموال',
      transferMoney: 'تحويل أموال',
      amount: 'المبلغ',
      enterAmount: 'أدخل المبلغ',
      paymentMethod: 'طريقة الدفع',
      creditCard: 'بطاقة ائتمان',
      debitCard: 'بطاقة خصم',
      bankTransfer: 'تحويل بنكي',
      digitalWallet: 'محفظة رقمية',
      transactionHistory: 'تاريخ المعاملات',
      transactionId: 'معرف المعاملة',
      date: 'التاريخ',
      description: 'الوصف',
      status: 'الحالة',
      completed: 'مكتمل',
      pending: 'معلق',
      failed: 'فشل',
      cancelled: 'ملغي',
      downloadStatement: 'تحميل كشف الحساب',
      paymentSettings: 'إعدادات الدفع',
      autoRecharge: 'الشحن التلقائي',
      lowBalanceAlert: 'تنبيه الرصيد المنخفض',
      transactionLimits: 'حدود المعاملات',
      dailyLimit: 'الحد اليومي',
      monthlyLimit: 'الحد الشهري',
      securitySettings: 'إعدادات الأمان',
      transactionPin: 'رقم المعاملة السري',
      changePinCode: 'تغيير الرقم السري',
    },

    // Points
    points: {
      title: 'نقاط الولاء',
      currentPoints: 'النقاط الحالية',
      pointsEarned: 'النقاط المكتسبة',
      pointsSpent: 'النقاط المستخدمة',
      pointsExpiring: 'النقاط المنتهية الصلاحية',
      earnPoints: 'اكسب نقاط',
      redeemPoints: 'استبدل النقاط',
      pointsHistory: 'تاريخ النقاط',
      earnedFrom: 'مكتسبة من',
      usedFor: 'مستخدمة في',
      booking: 'الحجز',
      referral: 'الإحالة',
      review: 'التقييم',
      bonus: 'مكافأة',
      rewardsProgram: 'برنامج المكافآت',
      loyaltyTiers: 'مستويات الولاء',
      bronze: 'برونزي',
      silver: 'فضي',
      gold: 'ذهبي',
      platinum: 'بلاتيني',
      nextTier: 'المستوى التالي',
      pointsToNextTier: 'النقاط للمستوى التالي',
      tierBenefits: 'مزايا المستوى',
      discount: 'خصم',
      exclusiveEvents: 'فعاليات حصرية',
      prioritySupport: 'دعم أولوية',
      freeShipping: 'شحن مجاني',
      
      // Followers System
      followers: 'متابعون',
      following: 'يتابع',
      follow: 'متابعة',
      unfollow: 'إلغاء المتابعة',
      followSuccess: 'تم المتابعة بنجاح',
      unfollowSuccess: 'تم إلغاء المتابعة',
      cannotFollowAdmin: 'لا يمكن متابعة المسؤولين',
      availableRewards: 'المكافآت المتاحة',
      redeemReward: 'استبدال المكافأة',
      pointsRequired: 'النقاط المطلوبة',
      rewardRedeemed: 'تم استبدال المكافأة',
      pointsExpiry: 'انتهاء صلاحية النقاط',
      expiringIn: 'تنتهي في',
      extendValidity: 'تمديد الصلاحية',
      transferPoints: 'تحويل نقاط',
      giftPoints: 'إهداء نقاط',
      pointsBalance: 'رصيد النقاط',
      earnRate: 'معدل الكسب',
      spendRate: 'معدل الإنفاق',
      conversionRate: 'معدل التحويل',
    },

    // My Events
    myEvents: {
      title: 'فعالياتي',
      bookedEvents: 'الفعاليات المحجوزة',
      upcomingEvents: 'الفعاليات القادمة',
      pastEvents: 'الفعاليات السابقة',
      cancelledEvents: 'الفعاليات الملغية',
      noEvents: 'لا توجد فعاليات',
      bookingConfirmed: 'تم تأكيد الحجز',
      bookingPending: 'الحجز معلق',
      bookingCancelled: 'تم إلغاء الحجز',
      eventCompleted: 'انتهت الفعالية',
      viewTicket: 'عرض التذكرة',
      downloadTicket: 'تحميل التذكرة',
      cancelBooking: 'إلغاء الحجز',
      reschedule: 'إعادة جدولة',
      addToCalendar: 'أضف للتقويم',
      shareEvent: 'شارك الفعالية',
      writeReview: 'اكتب تقييماً',
      eventReminder: 'تذكير الفعالية',
      checkIn: 'تسجيل الوصول',
      bookingReference: 'مرجع الحجز',
      bookingDate: 'تاريخ الحجز',
      paymentStatus: 'حالة الدفع',
      paid: 'مدفوع',
      unpaid: 'غير مدفوع',
      refunded: 'مسترد',
      ticketType: 'نوع التذكرة',
      general: 'عام',
      vip: 'كبار الشخصيات',
      premium: 'مميز',
      groupBooking: 'حجز جماعي',
      transferTicket: 'تحويل التذكرة',
      requestRefund: 'طلب استرداد',
      contactOrganizer: 'تواصل مع المنظم',
      eventDetails: 'تفاصيل الفعالية',
      bookingDetails: 'تفاصيل الحجز',
      attendeeInfo: 'معلومات الحضور',
      emergencyContact: 'جهة اتصال الطوارئ',
    },

    // Manage Events
    manageEvents: {
      title: 'إدارة الفعاليات',
      myEvents: 'فعالياتي',
      createNew: 'إنشاء جديد',
      allEvents: 'جميع الفعاليات',
      publishedEvents: 'الفعاليات المنشورة',
      draftEvents: 'المسودات',
      scheduledEvents: 'الفعاليات المجدولة',
      completedEvents: 'الفعاليات المكتملة',
      cancelledEvents: 'الفعاليات الملغية',
      eventStatus: 'حالة الفعالية',
      published: 'منشور',
      draft: 'مسودة',
      scheduled: 'مجدول',
      live: 'مباشر',
      completed: 'مكتمل',
      cancelled: 'ملغي',
      editEvent: 'تعديل الفعالية',
      duplicateEvent: 'نسخ الفعالية',
      publishEvent: 'نشر الفعالية',
      unpublishEvent: 'إلغاء نشر الفعالية',
      cancelEvent: 'إلغاء الفعالية',
      deleteEvent: 'حذف الفعالية',
      eventAnalytics: 'تحليلات الفعالية',
      bookingCount: 'عدد الحجوزات',
      revenue: 'الإيرادات',
      attendance: 'الحضور',
      registrations: 'التسجيلات',
      cancellations: 'الإلغاءات',
      noShows: 'عدم الحضور',
      attendeeList: 'قائمة الحضور',
      exportAttendees: 'تصدير قائمة الحضور',
      sendMessage: 'إرسال رسالة',
      messageAttendees: 'إرسال رسالة للحضور',
      eventQRCode: 'رمز QR للفعالية',
      checkInSystem: 'نظام تسجيل الوصول',
      eventSettings: 'إعدادات الفعالية',
      bookingSettings: 'إعدادات الحجز',
      paymentSettings: 'إعدادات الدفع',
      notificationSettings: 'إعدادات الإشعارات',
      refundRequests: 'طلبات الاسترداد',
      approveRefund: 'موافقة على الاسترداد',
      denyRefund: 'رفض الاسترداد',
      eventReports: 'تقارير الفعالية',
      financialReport: 'التقرير المالي',
      attendanceReport: 'تقرير الحضور',
      feedbackReport: 'تقرير التعليقات',
      downloadReport: 'تحميل التقرير',
    },

    // Manage Services
    manageServices: {
      title: 'إدارة الخدمات',
      myServices: 'خدماتي',
      createNew: 'إنشاء جديد',
      allServices: 'جميع الخدمات',
      activeServices: 'الخدمات النشطة',
      inactiveServices: 'الخدمات غير النشطة',
      draftServices: 'مسودات الخدمات',
      serviceStatus: 'حالة الخدمة',
      active: 'نشط',
      inactive: 'غير نشط',
      draft: 'مسودة',
      suspended: 'معلق',
      editService: 'تعديل الخدمة',
      duplicateService: 'نسخ الخدمة',
      activateService: 'تفعيل الخدمة',
      deactivateService: 'إلغاء تفعيل الخدمة',
      deleteService: 'حذف الخدمة',
      serviceAnalytics: 'تحليلات الخدمة',
      requestCount: 'عدد الطلبات',
      revenue: 'الإيرادات',
      completionRate: 'معدل الإنجاز',
      rating: 'التقييم',
      reviews: 'التقييمات',
      serviceRequests: 'طلبات الخدمة',
      pendingRequests: 'الطلبات المعلقة',
      acceptedRequests: 'الطلبات المقبولة',
      completedRequests: 'الطلبات المكتملة',
      rejectedRequests: 'الطلبات المرفوضة',
      acceptRequest: 'قبول الطلب',
      rejectRequest: 'رفض الطلب',
      completeRequest: 'إكمال الطلب',
      requestDetails: 'تفاصيل الطلب',
      clientInfo: 'معلومات العميل',
      serviceDate: 'تاريخ الخدمة',
      serviceTime: 'وقت الخدمة',
      serviceLocation: 'موقع الخدمة',
      specialRequests: 'طلبات خاصة',
      pricing: 'التسعير',
      basePrice: 'السعر الأساسي',
      additionalCharges: 'رسوم إضافية',
      totalAmount: 'المبلغ الإجمالي',
      paymentStatus: 'حالة الدفع',
      schedule: 'الجدولة',
      availability: 'التوفر',
      workingHours: 'ساعات العمل',
      breakTime: 'وقت الاستراحة',
      holidays: 'العطل',
      blockedDates: 'التواريخ المحجوبة',
      serviceReports: 'تقارير الخدمة',
      performanceReport: 'تقرير الأداء',
      clientReport: 'تقرير العملاء',
      revenueReport: 'تقرير الإيرادات',
    },

    // Organizer Dashboard
    organizerDashboard: {
      title: 'لوحة تحكم المنظم',
      welcome: 'مرحباً بك في لوحة تحكم المنظم',
      overview: 'نظرة عامة',
      quickStats: 'إحصائيات سريعة',
      totalEvents: 'إجمالي الفعاليات',
      activeEvents: 'الفعاليات النشطة',
      totalBookings: 'إجمالي الحجوزات',
      totalRevenue: 'إجمالي الإيرادات',
      upcomingEvents: 'الفعاليات القادمة',
      recentBookings: 'الحجوزات الأخيرة',
      eventPerformance: 'أداء الفعاليات',
      topPerformingEvents: 'الفعاليات الأكثر نجاحاً',
      bookingTrends: 'اتجاهات الحجز',
      monthlyRevenue: 'الإيرادات الشهرية',
      attendeeEngagement: 'تفاعل الحضور',
      quickActions: 'إجراءات سريعة',
      createEvent: 'إنشاء فعالية',
      viewAllEvents: 'عرض جميع الفعاليات',
      manageBookings: 'إدارة الحجوزات',
      viewReports: 'عرض التقارير',
      recentActivity: 'النشاط الأخير',
      newBooking: 'حجز جديد',
      cancellation: 'إلغاء',
      refundRequest: 'طلب استرداد',
      eventUpdate: 'تحديث فعالية',
      messageReceived: 'رسالة جديدة',
      pendingApprovals: 'موافقات معلقة',
      eventApplications: 'طلبات الفعاليات',
      refundRequests: 'طلبات الاسترداد',
      supportTickets: 'تذاكر الدعم',
      notifications: 'الإشعارات',
      messages: 'الرسائل',
      calendar: 'التقويم',
      eventCalendar: 'تقويم الفعاليات',
      bookingCalendar: 'تقويم الحجوزات',
      analytics: 'التحليلات',
      detailedAnalytics: 'تحليلات مفصلة',
      eventAnalytics: 'تحليلات الفعاليات',
      audienceAnalytics: 'تحليلات الجمهور',
      revenueAnalytics: 'تحليلات الإيرادات',
      settings: 'الإعدادات',
      organizerProfile: 'ملف المنظم',
      businessInfo: 'معلومات العمل',
      paymentSettings: 'إعدادات الدفع',
      notificationSettings: 'إعدادات الإشعارات',
    },

    // Provider Dashboard
    providerDashboard: {
      title: 'لوحة تحكم مقدم الخدمة',
      welcome: 'مرحباً بك في لوحة تحكم مقدم الخدمة',
      overview: 'نظرة عامة',
      quickStats: 'إحصائيات سريعة',
      totalServices: 'إجمالي الخدمات',
      activeServices: 'الخدمات النشطة',
      totalRequests: 'إجمالي الطلبات',
      totalEarnings: 'إجمالي الأرباح',
      serviceRequests: 'طلبات الخدمة',
      pendingRequests: 'الطلبات المعلقة',
      acceptedRequests: 'الطلبات المقبولة',
      completedRequests: 'الطلبات المكتملة',
      servicePerformance: 'أداء الخدمات',
      topServices: 'الخدمات الأكثر طلباً',
      clientSatisfaction: 'رضا العملاء',
      averageRating: 'متوسط التقييم',
      monthlyEarnings: 'الأرباح الشهرية',
      requestTrends: 'اتجاهات الطلبات',
      quickActions: 'إجراءات سريعة',
      createService: 'إنشاء خدمة',
      viewAllServices: 'عرض جميع الخدمات',
      manageRequests: 'إدارة الطلبات',
      viewEarnings: 'عرض الأرباح',
      recentActivity: 'النشاط الأخير',
      newRequest: 'طلب جديد',
      requestCompleted: 'طلب مكتمل',
      clientMessage: 'رسالة عميل',
      serviceUpdate: 'تحديث خدمة',
      paymentReceived: 'دفعة مستلمة',
      schedule: 'الجدولة',
      availability: 'التوفر',
      workingHours: 'ساعات العمل',
      appointments: 'المواعيد',
      blockedTimes: 'الأوقات المحجوبة',
      clients: 'العملاء',
      clientList: 'قائمة العملاء',
      clientHistory: 'تاريخ العملاء',
      clientFeedback: 'تعليقات العملاء',
      favoriteClients: 'العملاء المفضلون',
      analytics: 'التحليلات',
      serviceAnalytics: 'تحليلات الخدمة',
      clientAnalytics: 'تحليلات العملاء',
      earningsAnalytics: 'تحليلات الأرباح',
      performanceMetrics: 'مقاييس الأداء',
      settings: 'الإعدادات',
      providerProfile: 'ملف مقدم الخدمة',
      serviceSettings: 'إعدادات الخدمة',
      scheduleSettings: 'إعدادات الجدولة',
      paymentSettings: 'إعدادات الدفع',
      notificationSettings: 'إعدادات الإشعارات',
    },

    // Attendee Dashboard
    attendeeDashboard: {
      title: 'لوحة تحكم الحضور',
      welcome: 'مرحباً بك في لوحة تحكم الحضور',
      overview: 'نظرة عامة',
      quickStats: 'إحصائيات سريعة',
      eventsAttended: 'الفعاليات المحضورة',
      upcomingEvents: 'الفعاليات القادمة',
      totalSpent: 'إجمالي المنفق',
      loyaltyPoints: 'نقاط الولاء',
      myBookings: 'حجوزاتي',
      recentBookings: 'الحجوزات الأخيرة',
      nextEvent: 'الفعالية التالية',
      eventHistory: 'تاريخ الفعاليات',
      favoriteEvents: 'الفعاليات المفضلة',
      bookmarkedEvents: 'الفعاليات المحفوظة',
      recommendations: 'التوصيات',
      recommendedEvents: 'فعاليات موصى بها',
      similarEvents: 'فعاليات مشابهة',
      trendingEvents: 'الفعاليات الرائجة',
      quickActions: 'إجراءات سريعة',
      exploreEvents: 'استكشف الفعاليات',
      viewTickets: 'عرض التذاكر',
      checkWallet: 'فحص المحفظة',
      writeReview: 'اكتب تقييماً',
      recentActivity: 'النشاط الأخير',
      eventBooked: 'فعالية محجوزة',
      ticketDownloaded: 'تذكرة محملة',
      reviewSubmitted: 'تقييم مُرسل',
      pointsEarned: 'نقاط مكتسبة',
      eventCompleted: 'فعالية مكتملة',
      preferences: 'التفضيلات',
      eventPreferences: 'تفضيلات الفعاليات',
      notificationPreferences: 'تفضيلات الإشعارات',
      privacySettings: 'إعدادات الخصوصية',
      interests: 'الاهتمامات',
      favoriteCategories: 'الفئات المفضلة',
      locationPreferences: 'تفضيلات الموقع',
      budgetRange: 'نطاق الميزانية',
      calendar: 'التقويم',
      eventCalendar: 'تقويم الفعاليات',
      personalCalendar: 'التقويم الشخصي',
      reminders: 'التذكيرات',
      achievements: 'الإنجازات',
      badges: 'الشارات',
      milestones: 'المعالم',
      socialSharing: 'المشاركة الاجتماعية',
      attendeeNetwork: 'شبكة الحضور',
      friends: 'الأصدقاء',
      followers: 'المتابعون',
      following: 'المتابعين',
      groups: 'المجموعات',
      joinedGroups: 'المجموعات المنضم إليها',
      createGroup: 'إنشاء مجموعة',
      groupEvents: 'فعاليات المجموعة',
      groupDiscussions: 'نقاشات المجموعة',
      feedback: 'التعليقات',
      eventFeedback: 'تعليقات الفعالية',
      appFeedback: 'تعليقات التطبيق',
      suggestions: 'الاقتراحات',
      reportIssue: 'الإبلاغ عن مشكلة',
    },

    // Groups
    groups: {
      title: 'المجموعات',
      myGroups: 'مجموعاتي',
      joinedGroups: 'المجموعات المنضم إليها',
      createdGroups: 'المجموعات المُنشأة',
      discoverGroups: 'اكتشف المجموعات',
      popularGroups: 'المجموعات الشائعة',
      recommendedGroups: 'المجموعات الموصى بها',
      createGroup: 'إنشاء مجموعة',
      joinGroup: 'انضم للمجموعة',
      leaveGroup: 'ترك المجموعة',
      groupDetails: 'تفاصيل المجموعة',
      groupName: 'اسم المجموعة',
      groupDescription: 'وصف المجموعة',
      groupCategory: 'فئة المجموعة',
      groupType: 'نوع المجموعة',
      publicGroup: 'مجموعة عامة',
      privateGroup: 'مجموعة خاصة',
      members: 'الأعضاء',
      memberCount: 'عدد الأعضاء',
      admin: 'المدير',
      moderator: 'المشرف',
      member: 'عضو',
      groupEvents: 'فعاليات المجموعة',
      upcomingEvents: 'الفعاليات القادمة',
      pastEvents: 'الفعاليات السابقة',
      createEvent: 'إنشاء فعالية',
      discussions: 'النقاشات',
      newDiscussion: 'نقاش جديد',
      recentPosts: 'المنشورات الأخيرة',
      announcements: 'الإعلانات',
      groupRules: 'قوانين المجموعة',
      groupSettings: 'إعدادات المجموعة',
      inviteMembers: 'دعوة أعضاء',
      memberRequests: 'طلبات العضوية',
      approveRequest: 'قبول الطلب',
      rejectRequest: 'رفض الطلب',
      removeMember: 'إزالة عضو',
      promoteToAdmin: 'ترقية لمدير',
      promoteToModerator: 'ترقية لمشرف',
      demoteFromAdmin: 'تنزيل من الإدارة',
      demoteFromModerator: 'تنزيل من الإشراف',
      groupPhoto: 'صورة المجموعة',
      coverPhoto: 'صورة الغلاف',
      groupLocation: 'موقع المجموعة',
      groupInterests: 'اهتمامات المجموعة',
      joinRequest: 'طلب انضمام',
      requestSent: 'تم إرسال الطلب',
      requestPending: 'الطلب معلق',
      requestApproved: 'تم قبول الطلب',
      requestRejected: 'تم رفض الطلب',
      searchGroups: 'البحث في المجموعات',
      filterByCategory: 'تصفية حسب الفئة',
      filterByLocation: 'تصفية حسب الموقع',
      filterBySize: 'تصفية حسب الحجم',
      groupSize: 'حجم المجموعة',
      small: 'صغيرة',
      medium: 'متوسطة',
      large: 'كبيرة',
      groupActivity: 'نشاط المجموعة',
      activeGroups: 'المجموعات النشطة',
      inactiveGroups: 'المجموعات غير النشطة',
      groupNotifications: 'إشعارات المجموعة',
      muteNotifications: 'كتم الإشعارات',
      unmuteNotifications: 'إلغاء كتم الإشعارات',
      reportGroup: 'الإبلاغ عن المجموعة',
      blockGroup: 'حظر المجموعة',
      unblockGroup: 'إلغاء حظر المجموعة',
    },

    // Checkout
    checkout: {
      title: 'إتمام الحجز',
      bookingDetails: 'تفاصيل الحجز',
      eventDetails: 'تفاصيل الفعالية',
      serviceDetails: 'تفاصيل الخدمة',
      eventName: 'اسم الفعالية',
      serviceName: 'اسم الخدمة',
      dateTime: 'التاريخ والوقت',
      location: 'الموقع',
      duration: 'المدة',
      organizer: 'المنظم',
      provider: 'مقدم الخدمة',
      ticketType: 'نوع التذكرة',
      quantity: 'الكمية',
      price: 'السعر',
      subtotal: 'المجموع الفرعي',
      tax: 'الضريبة',
      serviceFee: 'رسوم الخدمة',
      processingFee: 'رسوم المعالجة',
      total: 'المجموع الكلي',
      discountCode: 'كود الخصم',
      applyDiscount: 'تطبيق الخصم',
      discountApplied: 'تم تطبيق الخصم',
      invalidCode: 'كود غير صالح',
      personalInfo: 'المعلومات الشخصية',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      emergencyContact: 'جهة اتصال الطوارئ',
      specialRequests: 'طلبات خاصة',
      additionalNotes: 'ملاحظات إضافية',
      paymentMethod: 'طريقة الدفع',
      creditCard: 'بطاقة ائتمان',
      debitCard: 'بطاقة خصم',
      digitalWallet: 'محفظة رقمية',
      bankTransfer: 'تحويل بنكي',
      cardNumber: 'رقم البطاقة',
      expiryDate: 'تاريخ الانتهاء',
      cvv: 'رمز الأمان',
      cardholderName: 'اسم حامل البطاقة',
      billingAddress: 'عنوان الفوترة',
      saveCard: 'حفظ البطاقة',
      savedCards: 'البطاقات المحفوظة',
      walletBalance: 'رصيد المحفظة',
      useWalletBalance: 'استخدام رصيد المحفظة',
      loyaltyPoints: 'نقاط الولاء',
      usePoints: 'استخدام النقاط',
      pointsValue: 'قيمة النقاط',
      termsAndConditions: 'الشروط والأحكام',
      agreeToTerms: 'أوافق على الشروط والأحكام',
      cancellationPolicy: 'سياسة الإلغاء',
      refundPolicy: 'سياسة الاسترداد',
      privacyPolicy: 'سياسة الخصوصية',
      proceedToPayment: 'المتابعة للدفع',
      confirmBooking: 'تأكيد الحجز',
      processing: 'جاري المعالجة...',
      paymentSuccessful: 'تم الدفع بنجاح',
      paymentFailed: 'فشل في الدفع',
      bookingConfirmed: 'تم تأكيد الحجز',
      bookingFailed: 'فشل في الحجز',
      bookingReference: 'مرجع الحجز',
      downloadTicket: 'تحميل التذكرة',
      sendTicketEmail: 'إرسال التذكرة بالبريد',
      addToCalendar: 'إضافة للتقويم',
      shareBooking: 'مشاركة الحجز',
      contactSupport: 'تواصل مع الدعم',
      securePayment: 'دفع آمن',
      encryptedConnection: 'اتصال مُشفر',
      securityGuarantee: 'ضمان الأمان',
      moneyBackGuarantee: 'ضمان استرداد الأموال',
    },

    // Checkout Success
    checkoutSuccess: {
      title: 'تم الحجز بنجاح!',
      successMessage: 'تهانينا! تم تأكيد حجزك بنجاح',
      bookingConfirmed: 'تم تأكيد الحجز',
      thankYou: 'شكراً لك',
      bookingDetails: 'تفاصيل الحجز',
      bookingReference: 'مرجع الحجز',
      eventName: 'اسم الفعالية',
      serviceName: 'اسم الخدمة',
      dateTime: 'التاريخ والوقت',
      location: 'الموقع',
      ticketType: 'نوع التذكرة',
      quantity: 'الكمية',
      totalPaid: 'المبلغ المدفوع',
      paymentMethod: 'طريقة الدفع',
      transactionId: 'معرف المعاملة',
      nextSteps: 'الخطوات التالية',
      downloadTicket: 'تحميل التذكرة',
      emailTicket: 'إرسال التذكرة بالبريد',
      addToCalendar: 'إضافة للتقويم',
      eventReminder: 'تذكير الفعالية',
      checkInInstructions: 'تعليمات تسجيل الوصول',
      contactInfo: 'معلومات التواصل',
      organizerContact: 'تواصل مع المنظم',
      providerContact: 'تواصل مع مقدم الخدمة',
      supportContact: 'تواصل مع الدعم',
      importantNotes: 'ملاحظات مهمة',
      arrivalTime: 'وقت الوصول',
      requiredItems: 'العناصر المطلوبة',
      dresscode: 'قواعد اللباس',
      ageRestrictions: 'قيود العمر',
      cancellationDeadline: 'موعد نهاية الإلغاء',
      refundPolicy: 'سياسة الاسترداد',
      weatherPolicy: 'سياسة الطقس',
      shareExperience: 'شارك تجربتك',
      socialMedia: 'وسائل التواصل الاجتماعي',
      hashtag: 'الهاشتاغ',
      tellFriends: 'أخبر أصدقائك',
      inviteFriends: 'ادع أصدقائك',
      referralBonus: 'مكافأة الإحالة',
      loyaltyPoints: 'نقاط الولاء',
      pointsEarned: 'النقاط المكتسبة',
      nextReward: 'المكافأة التالية',
      viewDashboard: 'عرض لوحة التحكم',
      exploreMore: 'استكشف المزيد',
      relatedEvents: 'فعاليات ذات صلة',
      relatedServices: 'خدمات ذات صلة',
      backToHome: 'العودة للرئيسية',
      continueExploring: 'تابع الاستكشاف',
      rateExperience: 'قيم التجربة',
      feedback: 'التعليقات',
      suggestions: 'الاقتراحات',
      problemResolution: 'حل المشاكل',
      receiptDownload: 'تحميل الإيصال',
      printReceipt: 'طباعة الإيصال',
      bookingHistory: 'تاريخ الحجوزات',
      manageBooking: 'إدارة الحجز',
      modifyBooking: 'تعديل الحجز',
      cancelBooking: 'إلغاء الحجز',
      transferBooking: 'تحويل الحجز',
    },

    // Tickets
    tickets: {
      title: 'تذاكري',
      activeTickets: 'التذاكر النشطة',
      upcomingEvents: 'الفعاليات القادمة',
      pastEvents: 'الفعاليات السابقة',
      expiredTickets: 'التذاكر المنتهية',
      cancelledTickets: 'التذاكر الملغية',
      noTickets: 'لا توجد تذاكر',
      ticketDetails: 'تفاصيل التذكرة',
      ticketNumber: 'رقم التذكرة',
      barcode: 'الباركود',
      qrCode: 'رمز QR',
      eventName: 'اسم الفعالية',
      eventDate: 'تاريخ الفعالية',
      eventTime: 'وقت الفعالية',
      venue: 'المكان',
      seatNumber: 'رقم المقعد',
      ticketType: 'نوع التذكرة',
      ticketPrice: 'سعر التذكرة',
      purchaseDate: 'تاريخ الشراء',
      ticketStatus: 'حالة التذكرة',
      valid: 'صالحة',
      used: 'مستخدمة',
      expired: 'منتهية',
      cancelled: 'ملغية',
      refunded: 'مستردة',
      downloadTicket: 'تحميل التذكرة',
      printTicket: 'طباعة التذكرة',
      shareTicket: 'مشاركة التذكرة',
      addToWallet: 'إضافة للمحفظة',
      addToCalendar: 'إضافة للتقويم',
      setReminder: 'تعيين تذكير',
      viewEvent: 'عرض الفعالية',
      eventDetails: 'تفاصيل الفعالية',
      organizerInfo: 'معلومات المنظم',
      contactOrganizer: 'تواصل مع المنظم',
      transferTicket: 'تحويل التذكرة',
      transferTo: 'تحويل إلى',
      transferFee: 'رسوم التحويل',
      confirmTransfer: 'تأكيد التحويل',
      cancelTransfer: 'إلغاء التحويل',
      refundTicket: 'استرداد التذكرة',
      refundAmount: 'مبلغ الاسترداد',
      refundReason: 'سبب الاسترداد',
      refundPolicy: 'سياسة الاسترداد',
      requestRefund: 'طلب الاسترداد',
      refundStatus: 'حالة الاسترداد',
      processingRefund: 'جاري معالجة الاسترداد',
      refundApproved: 'تم قبول الاسترداد',
      refundRejected: 'تم رفض الاسترداد',
      refundCompleted: 'تم إكمال الاسترداد',
      ticketValidation: 'تأكيد التذكرة',
      scanQR: 'مسح رمز QR',
      enterCode: 'إدخال الرمز',
      validationSuccess: 'تم التأكيد بنجاح',
      validationFailed: 'فشل في التأكيد',
      invalidTicket: 'تذكرة غير صالحة',
      duplicateTicket: 'تذكرة مكررة',
      usedTicket: 'تذكرة مستخدمة',
      expiredTicket: 'تذكرة منتهية الصلاحية',
      checkInTime: 'وقت تسجيل الوصول',
      checkOutTime: 'وقت تسجيل المغادرة',
      attendanceConfirmed: 'تم تأكيد الحضور',
      noShow: 'عدم حضور',
      lateArrival: 'وصول متأخر',
      earlyDeparture: 'مغادرة مبكرة',
      ticketNotes: 'ملاحظات التذكرة',
      specialInstructions: 'تعليمات خاصة',
      emergencyContact: 'جهة اتصال الطوارئ',
      healthRequirements: 'المتطلبات الصحية',
      accessibilityInfo: 'معلومات إمكانية الوصول',
      parkingInfo: 'معلومات المواقف',
      transportInfo: 'معلومات النقل',
      weatherUpdate: 'تحديث الطقس',
      eventChanges: 'تغييرات الفعالية',
      notifications: 'الإشعارات',
      ticketInsurance: 'تأمين التذكرة',
      insuranceCoverage: 'تغطية التأمين',
      claimInsurance: 'المطالبة بالتأمين',
      giftTicket: 'إهداء التذكرة',
      sendAsGift: 'إرسال كهدية',
      giftMessage: 'رسالة الهدية',
      giftRecipient: 'متلقي الهدية',
      unwrapGift: 'فتح الهدية',
      thankYouNote: 'رسالة شكر',
    },

    // Auth
    auth: {
      signIn: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      welcome: 'مرحباً بك',
      welcomeBack: 'مرحباً بعودتك',
      createAccount: 'إنشاء حساب جديد',
      joinCommunity: 'انضم إلى مجتمعنا',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      fullName: 'الاسم الكامل',
      firstName: 'الاسم الأول',
      lastName: 'اسم العائلة',
      phoneNumber: 'رقم الهاتف',
      dateOfBirth: 'تاريخ الميلاد',
      gender: 'الجنس',
      male: 'ذكر',
      female: 'أنثى',
      other: 'آخر',
      preferNotToSay: 'أفضل عدم الذكر',
      forgotPassword: 'نسيت كلمة المرور؟',
      resetPassword: 'إعادة تعيين كلمة المرور',
      sendResetLink: 'إرسال رابط الإعادة تعيين',
      enterEmail: 'أدخل بريدك الإلكتروني',
      enterPassword: 'أدخل كلمة المرور',
      enterFullName: 'أدخل اسمك الكامل',
      enterPhone: 'أدخل رقم هاتفك',
      rememberMe: 'تذكرني',
      staySignedIn: 'ابق مسجلاً للدخول',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      dontHaveAccount: 'ليس لديك حساب؟',
      signInHere: 'سجل دخولك هنا',
      signUpHere: 'أنشئ حساباً هنا',
      orContinueWith: 'أو تابع باستخدام',
      google: 'جوجل',
      facebook: 'فيسبوك',
      apple: 'أبل',
      twitter: 'تويتر',
      signInWithGoogle: 'تسجيل الدخول بجوجل',
      signInWithFacebook: 'تسجيل الدخول بفيسبوك',
      signInWithApple: 'تسجيل الدخول بأبل',
      termsAndConditions: 'الشروط والأحكام',
      privacyPolicy: 'سياسة الخصوصية',
      agreeToTerms: 'أوافق على',
      andPrivacyPolicy: 'وسياسة الخصوصية',
      bySigningUp: 'بإنشاء حساب، فإنك توافق على',
      accountCreated: 'تم إنشاء الحساب بنجاح',
      welcomeToAdrina: 'مرحباً بك في هواية',
      verifyEmail: 'تحقق من بريدك الإلكتروني',
      verificationSent: 'تم إرسال رابط التحقق إلى بريدك',
      resendVerification: 'إعادة إرسال رابط التحقق',
      emailVerified: 'تم تأكيد البريد الإلكتروني',
      emailNotVerified: 'البريد الإلكتروني غير مؤكد',
      verifyNow: 'تأكيد الآن',
      skipForNow: 'تخطي الآن',
      invalidCredentials: 'بيانات دخول غير صحيحة',
      emailAlreadyExists: 'البريد الإلكتروني موجود بالفعل',
      weakPassword: 'كلمة المرور ضعيفة',
      passwordMismatch: 'كلمات المرور غير متطابقة',
      passwordRequirements: 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
      emailFormat: 'تنسيق البريد الإلكتروني غير صحيح',
      requiredField: 'هذا الحقل مطلوب',
      accountLocked: 'الحساب مقفل',
      tooManyAttempts: 'محاولات كثيرة، حاول لاحقاً',
      accountDisabled: 'الحساب معطل',
      loginSuccessful: 'تم تسجيل الدخول بنجاح',
      logoutSuccessful: 'تم تسجيل الخروج بنجاح',
      passwordResetSent: 'تم إرسال رابط إعادة تعيين كلمة المرور',
      passwordChanged: 'تم تغيير كلمة المرور بنجاح',
      profileUpdated: 'تم تحديث الملف الشخصي',
      sessionExpired: 'انتهت صلاحية الجلسة',
      pleaseSignIn: 'يرجى تسجيل الدخول مرة أخرى',
      unauthorized: 'غير مخول بالوصول',
      accessDenied: 'تم رفض الوصول',
      networkError: 'خطأ في الشبكة',
      serverError: 'خطأ في الخادم',
      tryAgainLater: 'حاول مرة أخرى لاحقاً',
      contactSupport: 'تواصل مع الدعم',
      needHelp: 'تحتاج مساعدة؟',
      faq: 'الأسئلة الشائعة',
      support: 'الدعم',
      helpCenter: 'مركز المساعدة',
    },

    // Account Type
    accountType: {
      title: 'اختر نوع حسابك',
      subtitle: 'حدد النوع الذي يناسب احتياجاتك',
      selectType: 'اختر نوع الحساب',
      changeAnytime: 'يمكنك تغيير نوع حسابك في أي وقت',
      attendee: 'حضور',
      organizer: 'منظم فعاليات',
      provider: 'مقدم خدمة',
      admin: 'مدير النظام',
      attendeeDescription: 'احجز واحضر الفعاليات والأنشطة المختلفة',
      organizerDescription: 'نظم وأدر فعالياتك الخاصة وادع الآخرين للمشاركة',
      providerDescription: 'قدم خدماتك المتخصصة للمشاركين في الفعاليات',
      adminDescription: 'أدر المنصة والمستخدمين والمحتوى',
      attendeeFeatures: 'مميزات الحضور',
      organizerFeatures: 'مميزات المنظم',
      providerFeatures: 'مميزات مقدم الخدمة',
      adminFeatures: 'مميزات المدير',
      bookEvents: 'حجز الفعاليات',
      browseServices: 'تصفح الخدمات',
      earnPoints: 'كسب نقاط الولاء',
      writeReviews: 'كتابة التقييمات',
      joinGroups: 'الانضمام للمجموعات',
      personalCalendar: 'التقويم الشخصي',
      createEvents: 'إنشاء الفعاليات',
      manageBookings: 'إدارة الحجوزات',
      eventAnalytics: 'تحليلات الفعاليات',
      attendeeList: 'قوائم الحضور',
      eventPromotion: 'ترويج الفعاليات',
      revenueTracking: 'تتبع الإيرادات',
      offerServices: 'تقديم الخدمات',
      manageSchedule: 'إدارة الجدولة',
      clientManagement: 'إدارة العملاء',
      serviceAnalytics: 'تحليلات الخدمة',
      earningsTracking: 'تتبع الأرباح',
      professionalProfile: 'الملف المهني',
      userManagement: 'إدارة المستخدمين',
      contentModeration: 'إشراف المحتوى',
      systemSettings: 'إعدادات النظام',
      reportGeneration: 'إنشاء التقارير',
      securityManagement: 'إدارة الأمان',
      platformAnalytics: 'تحليلات المنصة',
      continue: 'متابعة',
      back: 'رجوع',
      confirm: 'تأكيد',
      typeSelected: 'تم اختيار نوع الحساب',
      setupProfile: 'إعداد الملف الشخصي',
      verificationRequired: 'مطلوب تحقق',
      documentUpload: 'رفع الوثائق',
      businessInfo: 'معلومات العمل',
      professionalCertification: 'الشهادة المهنية',
      backgroundCheck: 'فحص الخلفية',
      adminApproval: 'موافقة الإدارة',
      accountUnderReview: 'الحساب قيد المراجعة',
      approvalPending: 'في انتظار الموافقة',
      accountApproved: 'تم قبول الحساب',
      accountRejected: 'تم رفض الحساب',
      resubmitApplication: 'إعادة تقديم الطلب',
      contactAdmin: 'تواصل مع الإدارة',
      upgradeAccount: 'ترقية الحساب',
      downgradeAccount: 'تنزيل الحساب',
      switchAccountType: 'تغيير نوع الحساب',
      accountTypeChanged: 'تم تغيير نوع الحساب',
      restrictions: 'القيود',
      permissions: 'الصلاحيات',
      accessLevel: 'مستوى الوصول',
      featureAvailability: 'توفر الميزات',
      subscriptionRequired: 'مطلوب اشتراك',
      freeTier: 'المستوى المجاني',
      premiumTier: 'المستوى المميز',
      enterprise: 'المؤسسي',
      planDetails: 'تفاصيل الخطة',
      upgradeNow: 'الترقية الآن',
      comparePlans: 'مقارنة الخطط',
      startFreeTrial: 'بدء التجربة المجانية',
      cancelAnytime: 'يمكن الإلغاء في أي وقت',
      noCommitment: 'بدون التزام',
      moneyBackGuarantee: 'ضمان استرداد الأموال',
    },

    // Authentication
    authentication: {
      signIn: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      forgotPassword: 'نسيت كلمة المرور؟',
      resetPassword: 'إعادة تعيين كلمة المرور',
      createAccount: 'إنشاء حساب جديد',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      dontHaveAccount: 'ليس لديك حساب؟',
      signOut: 'تسجيل الخروج',
      accountType: 'نوع الحساب',
      selectAccountType: 'اختر نوع الحساب',
      attendee: 'حضور',
      organizer: 'منظم',
      provider: 'مقدم خدمة',
      admin: 'مدير النظام',
    },

    // Admin Panel
    admin: {
      title: 'لوحة تحكم الإدارة',
      dashboard: 'لوحة التحكم',
      overview: 'نظرة عامة',
      statistics: 'الإحصائيات',
      analytics: 'التحليلات',
      users: 'المستخدمون',
      usersManagement: 'إدارة المستخدمين',
      totalUsers: 'إجمالي المستخدمين',
      activeUsers: 'المستخدمون النشطون',
      newUsers: 'المستخدمون الجدد',
      blockedUsers: 'المستخدمون المحظورون',
      userDetails: 'تفاصيل المستخدم',
      blockUser: 'حظر المستخدم',
      unblockUser: 'إلغاء حظر المستخدم',
      deleteUser: 'حذف المستخدم',
      promoteToAdmin: 'ترقية لمدير',
      demoteFromAdmin: 'تنزيل من الإدارة',
      eventsManagement: 'إدارة الفعاليات',
      totalEvents: 'إجمالي الفعاليات',
      activeEvents: 'الفعاليات النشطة',
      pendingEvents: 'الفعاليات المعلقة',
      rejectedEvents: 'الفعاليات المرفوضة',
      approveEvent: 'قبول الفعالية',
      rejectEvent: 'رفض الفعالية',
      servicesManagement: 'إدارة الخدمات',
      totalServices: 'إجمالي الخدمات',
      activeServices: 'الخدمات النشطة',
      pendingServices: 'الخدمات المعلقة',
      approveService: 'قبول الخدمة',
      rejectService: 'رفض الخدمة',
      requestsManagement: 'إدارة الطلبات',
      allRequests: 'جميع الطلبات',
      serviceRequests: 'طلبات الخدمات',
      refundRequests: 'طلبات الاسترداد',
      supportRequests: 'طلبات الدعم',
      reportsManagement: 'إدارة التقارير',
      generateReport: 'إنشاء تقرير',
      downloadReport: 'تحميل التقرير',
      scheduledReports: 'التقارير المجدولة',
      revenueReport: 'تقرير الإيرادات',
      usageReport: 'تقرير الاستخدام',
      performanceReport: 'تقرير الأداء',
      systemSettings: 'إعدادات النظام',
      generalSettings: 'الإعدادات العامة',
      securitySettings: 'إعدادات الأمان',
      notificationSettings: 'إعدادات الإشعارات',
      paymentSettings: 'إعدادات الدفع',
      emailSettings: 'إعدادات البريد الإلكتروني',
      mapboxManagement: 'إدارة Mapbox',
      mapboxTokens: 'رموز Mapbox',
      addToken: 'إضافة رمز',
      editToken: 'تعديل الرمز',
      deleteToken: 'حذف الرمز',
      testToken: 'اختبار الرمز',
      tokenValid: 'الرمز صالح',
      tokenInvalid: 'الرمز غير صالح',
      translationManagement: 'إدارة الترجمات',
      addTranslation: 'إضافة ترجمة',
      editTranslation: 'تعديل الترجمة',
      deleteTranslation: 'حذف الترجمة',
      exportTranslations: 'تصدير الترجمات',
      importTranslations: 'استيراد الترجمات',
      errorLogs: 'سجل الأخطاء',
      viewLogs: 'عرض السجل',
      clearLogs: 'مسح السجل',
      downloadLogs: 'تحميل السجل',
      errorLevel: 'مستوى الخطأ',
      errorMessage: 'رسالة الخطأ',
      errorTime: 'وقت الخطأ',
      errorUser: 'المستخدم',
      databaseManagement: 'إدارة قاعدة البيانات',
      backupDatabase: 'نسخ احتياطي',
      restoreDatabase: 'استعادة',
      optimizeDatabase: 'تحسين',
      databaseStats: 'إحصائيات قاعدة البيانات',
      cacheManagement: 'إدارة الذاكرة المؤقتة',
      clearCache: 'مسح الذاكرة المؤقتة',
      cacheSize: 'حجم الذاكرة المؤقتة',
      cacheHitRate: 'معدل الإصابة',
      settingsSaved: 'تم حفظ الإعدادات بنجاح',
      tokenAdded: 'تم إضافة الرمز بنجاح',
      translationUpdated: 'تم تحديث الترجمة بنجاح',
      cacheCleared: 'تم مسح الذاكرة المؤقتة',
      backupCreated: 'تم إنشاء النسخة الاحتياطية',
    },

    // Follower Stats
    followerStats: {
      followers: 'متابعون',
      following: 'يتابع',
      followersCount: 'عدد المتابعين',
      followingCount: 'عدد المتابعين',
    },

    // Admin Panel
    adminPanel: {
      title: 'لوحة التحكم الإدارية',
      overview: 'نظرة عامة',
      users: 'المستخدمون',
      events: 'الفعاليات',
      services: 'الخدمات',
      categories: 'الفئات',
      finances: 'المالية',
      system: 'النظام',
      groups: 'المجموعات',
      activityLogs: 'سجل النشاطات',
      suspendedUsers: 'المستخدمون المعلقون',
      reportedMessages: 'الرسائل المبلغ عنها',
      stats: {
        totalUsers: 'إجمالي المستخدمين',
        userGrowth: 'نمو المستخدمين',
        totalEvents: 'إجمالي الفعاليات',
        eventGrowth: 'نمو الفعاليات',
        totalServices: 'إجمالي الخدمات',
        totalRevenue: 'إجمالي الإيرادات',
        revenueGrowth: 'نمو الإيرادات',
        activeBookings: 'الحجوزات النشطة',
        totalCategories: 'إجمالي الفئات',
        pendingReviews: 'التقييمات المعلقة',
      },
      pendingApprovals: 'الموافقات المعلقة',
      pendingEvents: 'الفعاليات المعلقة',
      pendingServices: 'الخدمات المعلقة',
      userManagement: 'إدارة المستخدمين',
      searchUsers: 'البحث عن المستخدمين',
      filterByRole: 'تصفية حسب الدور',
      filterByStatus: 'تصفية حسب الحالة',
      allRoles: 'جميع الأدوار',
      allStatuses: 'جميع الحالات',
      active: 'نشط',
      suspended: 'معلق',
      admin: 'مدير',
      organizer: 'منظم فعاليات',
      provider: 'مقدم خدمة',
      attendee: 'مشارك',
      actions: 'الإجراءات',
      viewDetails: 'عرض التفاصيل',
      editUser: 'تعديل المستخدم',
      suspendUser: 'تعليق المستخدم',
      unsuspendUser: 'إلغاء التعليق',
      deleteUser: 'حذف المستخدم',
      approve: 'قبول',
      reject: 'رفض',
      delete: 'حذف',
      view: 'عرض',
      bulkOperations: 'العمليات الجماعية',
      sendNotification: 'إرسال إشعار',
      systemSettings: 'إعدادات النظام',
      maintenanceMode: 'وضع الصيانة',
      enableMaintenanceMode: 'تفعيل وضع الصيانة',
      disableMaintenanceMode: 'تعطيل وضع الصيانة',
      restartSystem: 'إعادة تشغيل النظام',
      downloadBackup: 'تحميل نسخة احتياطية',
      serviceCategories: 'فئات الخدمات',
      eventCategories: 'فئات الفعاليات',
      regionalGroups: 'المجموعات الإقليمية',
      groupManagement: 'إدارة المجموعات',
      loading: 'جاري التحميل...',
      noData: 'لا توجد بيانات',
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      confirmSuspend: 'هل أنت متأكد من التعليق؟',
      confirmUnsuspend: 'هل أنت متأكد من إلغاء التعليق؟',
      success: 'تم بنجاح',
      error: 'حدث خطأ',
      name: 'الاسم',
      nameAr: 'الاسم (عربي)',
      nameEn: 'الاسم (English)',
      description: 'الوصف',
      status: 'الحالة',
      createdAt: 'تاريخ الإنشاء',
      updatedAt: 'تاريخ التحديث',
      members: 'الأعضاء',
      region: 'المنطقة',
      icon: 'الأيقونة',
      displayOrder: 'الترتيب',
      parentCategory: 'القسم الرئيسي',
      addCategory: 'إضافة فئة',
      editCategory: 'تعديل الفئة',
      addRegionalGroup: 'إضافة مجموعة إقليمية',
      editRegionalGroup: 'تعديل المجموعة',
      city: 'المدينة',
      selectCity: 'اختر المدينة',
      cancel: 'إلغاء',
      save: 'حفظ',
      update: 'تحديث',
      add: 'إضافة',
      suspendAccount: 'تعليق الحساب',
      suspendReason: 'سبب التعليق',
      suspendDuration: 'مدة التعليق',
      permanent: 'دائم',
      days7: '7 أيام',
      days30: '30 يوم',
      days90: '90 يوم',
      customDate: 'تاريخ مخصص',
      selectDate: 'اختر التاريخ',
      suspendedUntil: 'معلق حتى',
      suspendedBy: 'معلق بواسطة',
      suspendedAt: 'تاريخ التعليق',
      reason: 'السبب',
      removeSuspension: 'رفع التعليق',
      confirmRemoveSuspension: 'هل أنت متأكد من رفع التعليق؟',
      reportedMessagesTitle: 'الرسائل المبلغ عنها',
      reporter: 'المبلغ',
      sender: 'المرسل',
      messageType: 'نوع الرسالة',
      messageContent: 'محتوى الرسالة',
      reportDate: 'تاريخ البلاغ',
      reportStatus: 'حالة البلاغ',
      pending: 'قيد الانتظار',
      reviewing: 'قيد المراجعة',
      resolved: 'تم الحل',
      dismissed: 'تم الرفض',
      viewReport: 'عرض البلاغ',
      adminNotes: 'ملاحظات الإدارة',
      markAsReviewing: 'قيد المراجعة',
      markAsResolved: 'تم الحل',
      dismissReport: 'رفض البلاغ',
      additionalDetails: 'تفاصيل إضافية',
      groupType: 'نوع المجموعة',
      eventGroup: 'مجموعة فعالية',
      friendGroup: 'مجموعة أصدقاء',
      directMessage: 'رسالة مباشرة',
      eventTitle: 'عنوان الفعالية',
      assignedAdmin: 'المشرف المعين',
      currentMembers: 'الأعضاء الحاليون',
      maxMembers: 'الحد الأقصى للأعضاء',
      archived: 'مؤرشف',
      archiveGroup: 'أرشفة المجموعة',
      deleteGroup: 'حذف المجموعة',
      viewMembers: 'عرض الأعضاء',
      memberName: 'اسم العضو',
      memberRole: 'دور العضو',
      joinedAt: 'تاريخ الانضمام',
      memberStatus: 'حالة العضو',
      muted: 'مكتوم',
      unmute: 'إلغاء الكتم',
      mute: 'كتم',
      removeMember: 'إزالة العضو',
      owner: 'مالك',
      moderator: 'مشرف',
      member: 'عضو',
      searchMember: 'البحث عن عضو',
      activityLog: 'سجل النشاطات',
      adminName: 'اسم المسؤول',
      action: 'الإجراء',
      entityType: 'نوع الكيان',
      details: 'التفاصيل',
      date: 'التاريخ',
      userEmail: 'البريد الإلكتروني',
      eventName: 'اسم الفعالية',
      serviceName: 'اسم الخدمة',
      newRole: 'الدور الجديد',
      comment: 'تعليق',
      durationDays: 'المدة بالأيام',
      fullName: 'الاسم الكامل',
      phone: 'رقم الهاتف',
      bio: 'نبذة',
      contactInfo: 'معلومات الاتصال',
      accountInfo: 'معلومات الحساب',
      registrationDate: 'تاريخ التسجيل',
      suspensionInfo: 'معلومات التعليق',
      suspensionReason: 'سبب التعليق',
      points: 'النقاط',
      wallet: 'المحفظة',
      totalEarned: 'إجمالي الأرباح',
      totalPointsEarned: 'إجمالي النقاط المكتسبة',
      riyal: 'ريال',
      userDetails: 'تفاصيل المستخدم',
      editUserData: 'تعديل بيانات المستخدم',
      saving: 'جاري الحفظ...',
      notificationTitle: 'عنوان الإشعار',
      notificationMessage: 'رسالة الإشعار',
      notificationType: 'نوع الإشعار',
      targetAudience: 'الفئة المستهدفة',
      allUsers: 'جميع المستخدمين',
      attendees: 'الحضور',
      organizers: 'المنظمون',
      providers: 'مقدمو الخدمات',
      specificUser: 'مستخدم محدد',
      selectUser: 'اختر مستخدم',
      searchByNameOrId: 'ابحث بالاسم أو ID',
      noResults: 'لا توجد نتائج',
      sending: 'جاري الإرسال...',
      sendNotificationBtn: 'إرسال الإشعار',
      info: 'معلومات',
      warning: 'تحذير',
      bulkApprove: 'قبول المحدد',
      bulkReject: 'رفض المحدد',
      selectAll: 'تحديد الكل',
      clearSelection: 'إلغاء التحديد',
      selected: 'محدد',
      confirmBulkDelete: 'هل أنت متأكد من حذف العناصر المحددة؟',
      declineReason: 'سبب الرفض',
      decline: 'رفض',
      filterByState: 'تصفية حسب الحالة',
      allReports: 'جميع البلاغات',
    },

    // Loading states
    loading: {
      title: 'جاري التحميل...',
      description: 'يرجى الانتظار قليلاً',
      pageTitle: 'تحميل الصفحة',
      pageDescription: 'جاري تحميل المحتوى',
    },

    // Offline states
    offline: {
      title: 'غير متصل',
      description: 'تحقق من اتصال الإنترنت',
      retry: 'إعادة المحاولة',
    },

    // Error handling
    errors: {
      unexpected: 'حدث خطأ غير متوقع',
      unexpectedDescription: 'نأسف للإزعاج. حدث خطأ أثناء تحميل هذه الصفحة.',
      errorId: 'معرف الخطأ',
      developmentDetails: 'تفاصيل الخطأ (وضع التطوير)',
      retry: 'إعادة المحاولة',
      backToHome: 'العودة للرئيسية',
      copyDetails: 'نسخ التفاصيل',
      reportBug: 'الإبلاغ عن خطأ',
      persistentError: 'إذا استمر هذا الخطأ، يرجى التواصل مع فريق الدعم',
    },

    // Common translations
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    view: 'عرض',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    search: 'بحث',
    filter: 'تصفية',
    success: 'نجح',
    error: 'خطأ',
    warning: 'تحذير',
    info: 'معلومات',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    submit: 'إرسال',
    close: 'إغلاق',
  },
  en: {
    // Basic navigation
    home: 'Home',
    explore: 'Explore',
    services: 'Services',
    profile: 'Profile',
    settings: 'Settings',
    dashboard: 'Dashboard',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    
    // Loading states
    loading: {
      title: 'Loading...',
      description: 'Please wait a moment',
      pageTitle: 'Loading Page',
      pageDescription: 'Loading content',
    },

    // Offline states
    offline: {
      title: 'Offline',
      description: 'Check your internet connection',
      retry: 'Retry',
    },

    // Error handling
    errors: {
      unexpected: 'An unexpected error occurred',
      unexpectedDescription: 'We apologize for the inconvenience. An error occurred while loading this page.',
      errorId: 'Error ID',
      developmentDetails: 'Error Details (Development Mode)',
      retry: 'Retry',
      backToHome: 'Back to Home',
      copyDetails: 'Copy Details',
      reportBug: 'Report Bug',
      persistentError: 'If this error persists, please contact support',
    },

    // Follower Stats
    followerStats: {
      followers: 'Followers',
      following: 'Following',
      followersCount: 'Followers Count',
      followingCount: 'Following Count',
    },

    // Admin Panel
    adminPanel: {
      title: 'Admin Panel',
      overview: 'Overview',
      users: 'Users',
      events: 'Events',
      services: 'Services',
      categories: 'Categories',
      finances: 'Finances',
      system: 'System',
      groups: 'Groups',
      activityLogs: 'Activity Logs',
      suspendedUsers: 'Suspended Users',
      reportedMessages: 'Reported Messages',
      stats: {
        totalUsers: 'Total Users',
        userGrowth: 'User Growth',
        totalEvents: 'Total Events',
        eventGrowth: 'Event Growth',
        totalServices: 'Total Services',
        totalRevenue: 'Total Revenue',
        revenueGrowth: 'Revenue Growth',
        activeBookings: 'Active Bookings',
        totalCategories: 'Total Categories',
        pendingReviews: 'Pending Reviews',
      },
      pendingApprovals: 'Pending Approvals',
      pendingEvents: 'Pending Events',
      pendingServices: 'Pending Services',
      userManagement: 'User Management',
      searchUsers: 'Search Users',
      filterByRole: 'Filter by Role',
      filterByStatus: 'Filter by Status',
      allRoles: 'All Roles',
      allStatuses: 'All Statuses',
      active: 'Active',
      suspended: 'Suspended',
      admin: 'Admin',
      organizer: 'Organizer',
      provider: 'Provider',
      attendee: 'Attendee',
      actions: 'Actions',
      viewDetails: 'View Details',
      editUser: 'Edit User',
      suspendUser: 'Suspend User',
      unsuspendUser: 'Unsuspend',
      deleteUser: 'Delete User',
      approve: 'Approve',
      reject: 'Reject',
      delete: 'Delete',
      view: 'View',
      bulkOperations: 'Bulk Operations',
      sendNotification: 'Send Notification',
      systemSettings: 'System Settings',
      maintenanceMode: 'Maintenance Mode',
      enableMaintenanceMode: 'Enable Maintenance',
      disableMaintenanceMode: 'Disable Maintenance',
      restartSystem: 'Restart System',
      downloadBackup: 'Download Backup',
      serviceCategories: 'Service Categories',
      eventCategories: 'Event Categories',
      regionalGroups: 'Regional Groups',
      groupManagement: 'Group Management',
      loading: 'Loading...',
      noData: 'No data available',
      confirmDelete: 'Are you sure you want to delete?',
      confirmSuspend: 'Are you sure you want to suspend?',
      confirmUnsuspend: 'Are you sure you want to unsuspend?',
      success: 'Success',
      error: 'Error occurred',
      name: 'Name',
      nameAr: 'Name (Arabic)',
      nameEn: 'Name (English)',
      description: 'Description',
      status: 'Status',
      createdAt: 'Created At',
      updatedAt: 'Updated At',
      members: 'Members',
      region: 'Region',
      icon: 'Icon',
      displayOrder: 'Display Order',
      parentCategory: 'Parent Category',
      addCategory: 'Add Category',
      editCategory: 'Edit Category',
      addRegionalGroup: 'Add Regional Group',
      editRegionalGroup: 'Edit Group',
      city: 'City',
      selectCity: 'Select City',
      cancel: 'Cancel',
      save: 'Save',
      update: 'Update',
      add: 'Add',
      suspendAccount: 'Suspend Account',
      suspendReason: 'Suspension Reason',
      suspendDuration: 'Suspension Duration',
      permanent: 'Permanent',
      days7: '7 Days',
      days30: '30 Days',
      days90: '90 Days',
      customDate: 'Custom Date',
      selectDate: 'Select Date',
      suspendedUntil: 'Suspended Until',
      suspendedBy: 'Suspended By',
      suspendedAt: 'Suspended At',
      reason: 'Reason',
      removeSuspension: 'Remove Suspension',
      confirmRemoveSuspension: 'Confirm Remove Suspension?',
      reportedMessagesTitle: 'Reported Messages',
      reporter: 'Reporter',
      sender: 'Sender',
      messageType: 'Message Type',
      messageContent: 'Message Content',
      reportDate: 'Report Date',
      reportStatus: 'Report Status',
      pending: 'Pending',
      reviewing: 'Reviewing',
      resolved: 'Resolved',
      dismissed: 'Dismissed',
      viewReport: 'View Report',
      adminNotes: 'Admin Notes',
      markAsReviewing: 'Mark as Reviewing',
      markAsResolved: 'Mark as Resolved',
      dismissReport: 'Dismiss Report',
      additionalDetails: 'Additional Details',
      groupType: 'Group Type',
      eventGroup: 'Event Group',
      friendGroup: 'Friend Group',
      directMessage: 'Direct Message',
      eventTitle: 'Event Title',
      assignedAdmin: 'Assigned Admin',
      currentMembers: 'Current Members',
      maxMembers: 'Max Members',
      archived: 'Archived',
      archiveGroup: 'Archive Group',
      deleteGroup: 'Delete Group',
      viewMembers: 'View Members',
      memberName: 'Member Name',
      memberRole: 'Member Role',
      joinedAt: 'Joined At',
      memberStatus: 'Member Status',
      muted: 'Muted',
      unmute: 'Unmute',
      mute: 'Mute',
      removeMember: 'Remove Member',
      owner: 'Owner',
      moderator: 'Moderator',
      member: 'Member',
      searchMember: 'Search Member',
      activityLog: 'Activity Log',
      adminName: 'Admin Name',
      action: 'Action',
      entityType: 'Entity Type',
      details: 'Details',
      date: 'Date',
      userEmail: 'Email',
      eventName: 'Event Name',
      serviceName: 'Service Name',
      newRole: 'New Role',
      comment: 'Comment',
      durationDays: 'Duration (Days)',
      fullName: 'Full Name',
      phone: 'Phone',
      bio: 'Bio',
      contactInfo: 'Contact Info',
      accountInfo: 'Account Info',
      registrationDate: 'Registration Date',
      suspensionInfo: 'Suspension Info',
      suspensionReason: 'Suspension Reason',
      points: 'Points',
      wallet: 'Wallet',
      totalEarned: 'Total Earned',
      totalPointsEarned: 'Total Points Earned',
      riyal: 'SAR',
      userDetails: 'User Details',
      editUserData: 'Edit User Data',
      saving: 'Saving...',
      notificationTitle: 'Notification Title',
      notificationMessage: 'Notification Message',
      notificationType: 'Notification Type',
      targetAudience: 'Target Audience',
      allUsers: 'All Users',
      attendees: 'Attendees',
      organizers: 'Organizers',
      providers: 'Providers',
      specificUser: 'Specific User',
      selectUser: 'Select User',
      searchByNameOrId: 'Search by Name or ID',
      noResults: 'No Results',
      sending: 'Sending...',
      sendNotificationBtn: 'Send Notification',
      info: 'Info',
      warning: 'Warning',
      bulkApprove: 'Approve Selected',
      bulkReject: 'Reject Selected',
      selectAll: 'Select All',
      clearSelection: 'Clear Selection',
      selected: 'Selected',
      confirmBulkDelete: 'Confirm delete selected items?',
      declineReason: 'Decline Reason',
      decline: 'Decline',
      filterByState: 'Filter by State',
      allReports: 'All Reports',
    },

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    submit: 'Submit',
    close: 'Close',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'ar' | 'en'>('ar');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as 'ar' | 'en';
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const handleSetLanguage = (lang: 'ar' | 'en') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, fallback?: string) => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
      if (value === undefined) return fallback ?? key;
    }
    
    return (value as string) || fallback || key;
  };

  const value = {
    language,
    setLanguage: handleSetLanguage,
    t,
    isRTL: language === 'ar'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguageContext  = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
