// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzuppbjtxmfrgutyagev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dXBwYmp0eG1mcmd1dHlhZ2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzc2MTUsImV4cCI6MjA3MTc1MzYxNX0.9IbzvPg2YWMDBj9SQ5QXz7GAQmWV4VCzIJJpct72KG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});