// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxtujqmvvcfrelfjqina.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dHVqcW12dmNmcmVsZmpxaW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MDkzNDgsImV4cCI6MjA5ODA4NTM0OH0.hrLuo5MrmQS9fLlo3e4lO-XW8wA8Fz_1ytUa89U8ZVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});